name: Haskell-C-Compiler
version: 0.1.0
dependencies:
  - base >= 4.7 && < 5

# system-ghc: true

library:
  source-dirs:
    - src
  exposed-modules:
    - Parser
    - Codegen
    - Emit
  dependencies:
    - parsec
    - llvm-hs     
    - llvm-hs-pure 
    - mtl >= 2.1.3
    - containers
    - bytestring >=0.10 

executable:
  main: app/Main.hs
  dependencies:
    - Haskell-C-Compiler
    - parsec
    - base
    - mtl >= 2.1.3
    - haskeline >= 0.7.1.2
    - llvm-hs     
    - llvm-hs-pure 
  # modules:
  #   - Lexer

# test-suite my-tests:
#   type: exitcode-stdio-1.0
#   main: test/Spec.hs
#   dependencies:
#     - Token

# source-repository head
#   type: git
#   location: https://github.com/user/my-project.git

